# 服务端口号
server:
  port: 40001

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bloodline?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: ${pw}

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.cq.httpapi.demo.dao
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范

#logging:
#  level:
#    com.cq.httpapi.demo.dao: debug
##    com.cq.httpapi.demo.myhandler: debug

logging:
#  file: C:/Users/Administrator/Desktop/logTest/log.txt
#  level:
#    com.cq.httpapi.demo.dao: info
#    com.cq.httpapi.demo.myhandler: info
  config: classpath:logback-dev.xml